# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a263fe5b41007b0de87cae35aef621ed578dbf021b1b50a4432e4be3453f5b93059cd9fa68bc645f73ad26ca6f98338e9bc295fd373035b051022643ecc20a5c

test:
  secret_key_base: bf8aec19d5d958a93d8aa94a329fad3d2970e88f6880ec8d19758b6701185765b03d6d481c87a0fd20c174edf0838a188e874a6720db18653947136d9a0a77e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
