# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3f5cd68bf3829c8646685e48cb72d5f9f3e8e5b723087b375316c3a4c03979e5d5c5a0e991f662615b94648d61689ada4f93aee49843bd8405480fdda849cd8

test:
  secret_key_base: 1a94ed361d160550e74613d4975300ba1cd894d8b86091a9c4cf25ea6590f62bfa98bcafc41215a0b4212e06df994fa5d0a59490eab17154dbe07ce0c6e55f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
