# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f694e5c5d033b66d0b84c13c4bb725459c191e936ba5fb16e334304bd766267a753a3bb66fb9682de37b6a16705a9772bd55d90925cbd19bea674b622884d8

test:
  secret_key_base: e3f8975fbf261f0e721ccae30de79e77ee867c5ecc00affd2a8cc25c1159a68fac258bc2db6a3c87b8d876b8f8b67dbaf353d98089adf3d4336c4c3647075ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
